# Numpy简介

In [1]:
from numpy import *

在numpy中，一种新的用于向量，矩阵和更高维度的数据集叫做数组(array)

## Numpy 数组的创建


有很多方式来初始化新的numpy数组：
- python列表或元组
- 使用专用于产生numpy数组的功能，如arange,linspace等
- 从文件中读取

### 从列表
要创建python列表新向量和矩阵数组，我们可以使用numpy.array功能

In [2]:
#矢量:该参数数组功能是一个python列表
V=array([1,2,3,4])
V

array([1, 2, 3, 4])

#### 矩阵：参数到数组的功能是一个嵌套python列表

In [3]:
M=array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [4]:
type(V),type(M)

(numpy.ndarray, numpy.ndarray)

V和M之间的差别只是它们的形状，我们可以通过ndarray.shape获取数组的形状信息

In [5]:
V.shape,M.shape

((4,), (2, 2))

得到数组中元素的数量可以使用ndarray.size

In [6]:
M.size,V.size

(4, 4)

等价地，可以使用numpy.shape和numpy.size

In [7]:
shape(M),shape(V),size(M),size(V)

((2, 2), (4,), 4, 4)

为什么不直接用Python列表来代替创建新数组呢?
- python列表非常普遍，它们可以包含任何类型对象。是动态类型，不支持python列表的数学函数，如矩阵和标量积
- numpy数组静态且均匀，元素类型在创建时确定
- numpy节约内存
- numpy可用在编译语言快速实现的数学函数

使用dtype(数据类型):

In [8]:
M.dtype

dtype('int64')

我们无法将错误类型的值赋给Numpy中的元素

In [9]:
M[0,0]="hello"

ValueError: invalid literal for int() with base 10: 'hello'

另外，如果愿意，当我们创建数组时，可以明确定义数组数据的类型，使用dtype关键字:

In [11]:
M=array([[1,2],[3,4]],dtype=complex)
M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

普通型可与DTYPE使用的是: int, float, complex, bool, object, 等.

我们还可以定义的数据类型的位大小，例如: int64, int16, float128, complex128.



## 使用数组生成功能
对于较大的数组，使用python列表手动初始化是不现实的，相反，我们可以使用numpy的不同功能产生不同的数组

**arange**

In [12]:
x=arange(0,10,1)#arguments:start,stop,step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**linspace和logspace**

In [13]:
#使用linspace创建等差数列
linspace(0,10,25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [14]:
#使用logspace创建等比数列
logspace(0,10,10,base=e)

array([  1.00000000e+00,   3.03773178e+00,   9.22781435e+00,
         2.80316249e+01,   8.51525577e+01,   2.58670631e+02,
         7.85771994e+02,   2.38696456e+03,   7.25095809e+03,
         2.20264658e+04])

**mgrid**

In [15]:
x,y=mgrid[0:5,0:5]
x,y

(array([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]]), array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]))

**随机数据**

In [16]:
#均匀随机数[0,1]
random.rand(5,5)

array([[ 0.8021789 ,  0.58839925,  0.00870708,  0.85395424,  0.76728913],
       [ 0.98915005,  0.59334915,  0.69715593,  0.41077012,  0.94211573],
       [ 0.51269251,  0.36414971,  0.94613768,  0.4282178 ,  0.44895213],
       [ 0.20074179,  0.03587409,  0.96199774,  0.30874372,  0.52212117],
       [ 0.8483251 ,  0.001537  ,  0.61333676,  0.85152961,  0.08063525]])

In [17]:
#标准正态分布的随机数
random.randn(5,5)

array([[ 1.04741534,  0.98609433, -1.25049459, -1.66810248,  1.45251336],
       [-0.39630675, -0.82987852, -1.32952141, -1.29399789, -0.52884595],
       [ 0.07251537, -0.31629646, -0.45469464,  0.25865968,  0.02493615],
       [-1.18168121,  0.06275337, -0.28309683, -0.23428347,  0.11024831],
       [ 0.4992789 ,  0.51366249,  0.34372447,  0.93199532,  1.28665819]])

**diag**

In [18]:
#对角矩阵
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
#对角线与来自主对角线的偏移
diag([1,2,3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

**zeros and ones**

In [20]:
zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])