# numpy

### 线性代数模块(linalg)

在深度学习相关的数据处理和运算中，线性代数模块（linalg）是最常用的之一。
结合numpy提供的基本函数，可以对向量，矩阵，或是说多维张量进行一些基本的运算：

In [2]:
import numpy as np

In [3]:
a=np.array([3,4])
np.linalg.norm(a)  #范数norm

5.0

In [4]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
c=np.array([1,0,1])

In [6]:
#矩阵和向量之间的乘法
np.dot(b,c),np.dot(c,b.T),np.dot(b,c.T)#原来可以自适应乘啊=-=

(array([ 4, 10, 16]), array([ 4, 10, 16]), array([ 4, 10, 16]))

> 矩阵的迹：一个n*n的矩阵A的主对角线（左上方->右下方）上各个元素的总和   

In [7]:
#矩阵的迹
np.trace(b)

15

In [8]:
#行列式的值
np.linalg.det(b)

-9.5161973539299405e-16

In [9]:
#矩阵的秩
np.linalg.matrix_rank(b)

2

In [10]:
d=np.array([
    [2,1],
    [1,2]
])

In [11]:
'''
对正定矩阵求本征值和本征向量
本征值为u，array([ 3.,  1.])
本征向量构成的二维array为v，
array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])
是沿着45°方向
eig()是一般情况的本征值分解，对于更常见的对称实数矩阵，
eigh()更快且更稳定，不过输出的值的顺序和eig()是相反的
'''
#看不懂啊，，马一下后补
u,v=np.linalg.eig(d)
# Cholesky分解并重建
l = np.linalg.cholesky(d)

'''
array([[ 2.,  1.],
       [ 1.,  2.]])
'''
np.dot(l, l.T)

e = np.array([
    [1, 2],
    [3, 4]
])
# 对不正定矩阵，进行SVD分解并重建
U, s, V = np.linalg.svd(e)

S = np.array([
    [s[0], 0],
    [0, s[1]]
])

'''
array([[ 1.,  2.],
       [ 3.,  4.]])
'''
np.dot(U, np.dot(S, V))

array([[ 1.,  2.],
       [ 3.,  4.]])

### 随机模块

In [12]:
import numpy.random as random

In [13]:
#设置随机数种子
random.seed(42)

In [14]:
#产生一个1*3，[0,1)之间的浮点型随机数
random.rand(1,3)

array([[ 0.37454012,  0.95071431,  0.73199394]])

In [15]:
#产生一个[0,1)之间的浮点型随机数
random.rand()

0.5986584841970366

In [16]:
#下面四个没有区别，都是按照指定大小产生[0,1)之间的浮点型随机数
random.random((3,3)),random.sample((3,3)),random.random_sample((3,3)),random.ranf((3,3))

(array([[ 0.15601864,  0.15599452,  0.05808361],
        [ 0.86617615,  0.60111501,  0.70807258],
        [ 0.02058449,  0.96990985,  0.83244264]]),
 array([[ 0.21233911,  0.18182497,  0.18340451],
        [ 0.30424224,  0.52475643,  0.43194502],
        [ 0.29122914,  0.61185289,  0.13949386]]),
 array([[ 0.29214465,  0.36636184,  0.45606998],
        [ 0.78517596,  0.19967378,  0.51423444],
        [ 0.59241457,  0.04645041,  0.60754485]]),
 array([[ 0.17052412,  0.06505159,  0.94888554],
        [ 0.96563203,  0.80839735,  0.30461377],
        [ 0.09767211,  0.68423303,  0.44015249]]))

In [18]:
#产生10个[1,6)之间的浮点型随机数
5*random.random(10)+1,random.uniform(1,6,10)

(array([ 5.84792314,  4.87566412,  5.69749471,  5.47413675,  3.98949989,
         5.60937118,  1.44246251,  1.97991431,  1.22613644,  2.62665165]),
 array([ 2.94338645,  2.35674516,  5.14368755,  2.78376663,  2.40467255,
         3.71348042,  1.70462112,  5.0109849 ,  1.37275322,  5.93443468]))

In [19]:
#产生10个[1,6)之间的整型随机数
random.randint(1,6,10)

array([1, 4, 3, 3, 1, 3, 3, 1, 3, 5])

In [20]:
#产生2*5的标准正态分布样本
random.normal(size=(5,2))

array([[ 0.21158701,  0.59704465],
       [-0.89633518, -0.11198782],
       [ 1.46894129, -1.12389833],
       [ 0.9500054 ,  1.72651647],
       [ 0.45788508, -1.68428738]])

In [21]:
#产生5个，n=5,p=0.5的二项分布样本
random.binomial(n=5,p=0.5,size=5)

array([2, 5, 4, 3, 2])

In [23]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#从a中有放回的随机采样7个
random.choice(a,7)

array([6, 8, 9, 9, 2, 6, 0])

In [25]:
#从a中无放回的随机采样7个
random.choice(a,7,replace=False)

array([7, 1, 8, 0, 2, 6, 4])

In [26]:
#对a进行乱序并返回一个新的array
b=random.permutation(a)
b

array([8, 9, 4, 0, 7, 1, 3, 5, 2, 6])

In [28]:
#对a进行in-place乱序
random.shuffle(a)
a

array([2, 1, 3, 8, 5, 6, 0, 9, 7, 4])

In [29]:
# 生成一个长度为9的随机bytes序列并作为str返回
random.bytes(9)

b'\xbd\xefVmx\x1a"\x00s'