# Numpy
-----------*科学计算包*

## 基本类型(array)

array,numpy中基础数据结构--数组
关键属性--维度&元素类型

In [1]:
import numpy as np

a=[1,2,3,4]
b=np.array(a)
type(b)

numpy.ndarray

In [2]:
b.shape

(4,)

In [3]:
print("argmax: %f,max: %f,mean: %f"%(b.argmax(),b.max(),b.mean()))

argmax: 3.000000,max: 4.000000,mean: 2.500000


In [4]:
c=[[1,2],[3,4]]
d=np.array(c)
d.shape

(2, 2)

In [5]:
d.max(axis=0)

array([3, 4])

In [6]:
d.flatten() # 展开一个numpy数组为1维数组，array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
np.ravel(c) # 展开一个可以解析的结构为1维数组，array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
# 3x3的浮点型2维数组，并且初始化所有元素值为1
e = np.ones((3, 3), dtype=np.float)
# 创建一个一维数组，元素值是把3重复4次，array([3, 3, 3, 3])
f = np.repeat(3, 4)
# 2x2x3的无符号8位整型3维数组，并且初始化所有元素值为0
g = np.zeros((2, 2, 3), dtype=np.uint8)

In [9]:
g.shape

(2, 2, 3)

In [10]:
h = g.astype(np.float)  # 用另一种类型表示
h

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [11]:
l = np.arange(10)      	# 类似range，array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
m = np.linspace(0, 6, 5)# 等差数列，0到6之间5个取值，array([ 0., 1.5, 3., 4.5, 6.])
m

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [13]:
p = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]]
)
np.save('p.npy', p)     # 保存到文件

In [14]:
q = np.load('p.npy')    # 从文件读取
q

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
b = a[1][1][1]  # 17
b

17

In [17]:
c = a[:, 2, :]
c

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [18]:
f = a[:, 1:, 1:-1]#为啥？不是逆序...emmm...好吧我傻了-n是倒数第n个
f

array([[[ 5,  6],
        [ 9, 10]],

       [[17, 18],
        [21, 22]]])

In [19]:
g=np.split(np.arange(9),3)
g

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [20]:
'''
按照下标位置进行划分
[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8])]
'''
h = np.split(np.arange(9), [2, -3])
h

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8])]

In [21]:
l0 = np.arange(6).reshape((2, 3))
l0

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
l1 = np.arange(6, 12).reshape((2, 3))
l1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

- vstack是指沿着纵轴拼接两个array，vertical
- hstack是指沿着横轴拼接两个array，horizontal
- 更广义的拼接用concatenate实现，horizontal后的两句依次等效于vstack和hstack
- stack不是拼接而是在输入array的基础上增加一个新的维度


In [23]:
m=np.vstack((l0,l1))
p=np.hstack((l0,l1))
print("vstack",m)
print("hstack",p)

vstack [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
hstack [[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [24]:
q=np.concatenate((l0,l1))
q

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
r=np.concatenate((l0,l1),axis=1)
r

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [26]:
s = np.stack((l0, l1))
s

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
'''
按指定轴进行转置
array([[[ 0,  3],
        [ 6,  9]],

       [[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]]])
'''
t = s.transpose((2, 0, 1))
t

array([[[ 0,  3],
        [ 6,  9]],

       [[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]]])

In [28]:
u=a[0].transpose()
u

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
u=a[0].T   #ahaha 转置还能这样啊
u

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [30]:
'''
逆时针旋转90度，第二个参数是旋转次数
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
'''
v=np.rot90(u,3)
v

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [31]:
'''
沿纵轴左右翻转
array([[ 8,  4,  0],
       [ 9,  5,  1],
       [10,  6,  2],
       [11,  7,  3]])
'''
w = np.fliplr(u)
w

array([[ 8,  4,  0],
       [ 9,  5,  1],
       [10,  6,  2],
       [11,  7,  3]])

In [32]:
'''
沿水平轴上下翻转
array([[ 3,  7, 11],
       [ 2,  6, 10],
       [ 1,  5,  9],
       [ 0,  4,  8]])
'''
x = np.flipud(u)
x

array([[ 3,  7, 11],
       [ 2,  6, 10],
       [ 1,  5,  9],
       [ 0,  4,  8]])

In [33]:
'''
按照一维顺序滚动位移
array([[11,  0,  4],
       [ 8,  1,  5],
       [ 9,  2,  6],
       [10,  3,  7]])
'''
y = np.roll(u, 1)
y

array([[11,  0,  4],
       [ 8,  1,  5],
       [ 9,  2,  6],
       [10,  3,  7]])

In [34]:
u

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [35]:
'''
按照指定轴滚动位移
array([[ 8,  0,  4],
       [ 9,  1,  5],
       [10,  2,  6],
       [11,  3,  7]])
'''
z = np.roll(u, 1, axis=1)
z

array([[ 8,  0,  4],
       [ 9,  1,  5],
       [10,  2,  6],
       [11,  3,  7]])

对于一维的array所有Python列表支持的下标相关的方法array也都支持，所以在此没有特别列出。

In [36]:
# 绝对值，1
a = np.abs(-1)
# sin函数，1.0
b = np.sin(np.pi/2)

# tanh逆函数，0.50000107157840523
c = np.arctanh(0.462118)

# e为底的指数函数，20.085536923187668
d = np.exp(3)

# 2的3次方，8
f = np.power(2, 3)

# 点积，1*3+2*4=11
g = np.dot([1, 2], [3, 4])

# 开方，5
h = np.sqrt(25)

# 求和，10
l = np.sum([1, 2, 3, 4])

# 平均值，5.5
m = np.mean([4, 5, 6, 7])

# 标准差，0.96824583655185426
p = np.std([1, 2, 3, 2, 1, 3, 2, 0])
a,b,c,d,e,f,g,h,l,m,p

(1, 1.0, 0.50000107157840534, 20.085536923187668, array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), 8, 11, 5.0, 10, 5.5, 0.96824583655185426)

对于array，默认执行对位运算。涉及到多个array的对位运算需要array的维度一致，如果一个array的维度和另一个array的子维度一致，则在没有对齐的维度上分别执行对位运算，这种机制叫做广播（broadcasting）

In [37]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[1,2,3],
           [1,2,3]])

In [39]:
'''
维度一样的array，对位计算
'''
a+b,a-b,a*b,a/b,a**2,a**b

(array([[2, 4, 6],
        [5, 7, 9]]), array([[0, 0, 0],
        [3, 3, 3]]), array([[ 1,  4,  9],
        [ 4, 10, 18]]), array([[ 1. ,  1. ,  1. ],
        [ 4. ,  2.5,  2. ]]), array([[ 1,  4,  9],
        [16, 25, 36]]), array([[  1,   4,  27],
        [  4,  25, 216]]))

In [40]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
d = np.array([2, 2, 2])


In [46]:
'''
广播机制让计算的表达式保持简洁
d和c的每一行分别进行运算
array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])
'''
c + d, c*d ,c-1

(array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]), array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]]), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))